services:
  template-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_SERVER_URL: ${VITE_SERVER_URL}
        VITE_SERVER_URL_INTERNAL: ${VITE_SERVER_URL_INTERNAL}
    depends_on:
      - template-server
    environment:
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      VITE_SERVER_URL_INTERNAL: ${VITE_SERVER_URL_INTERNAL}

  template-server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_REGION: ${S3_REGION}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BACKEND_URL: ${BACKEND_URL}
      MAIN_ADMIN_EMAIL: ${MAIN_ADMIN_EMAIL} 
      MAIN_ADMIN_PASSWORD: ${MAIN_ADMIN_PASSWORD}
      CORS_COOKIE_DOMAIN: ${CORS_COOKIE_DOMAIN}

